### ISSUE TITLE
Improvements for large scale validation tools

### ISSUE THREAD

**Issue by stefsmeets** [duqtools/duqtools#432]
#423 implements a prototype for large scale validation. This is a list of potential enhancements for improvement:

- [x] Setup runs dir in template
- [ ] #519
- [x] #511 
- [x] Embed name of entry in `data.csv` in submit command so that it can be identified in slurm -> #509 
- [x] Reduce verbosity of CLI interface code, there is a lot of boilerplate
- [x] `duqduq setup --force` -> overwrite existing runs -> #483 
- [x] `duqduq setup` -> Add logging, `op_queue` support? -> #483 
- [x] `duqduq summary` -> Generate summary table with run status (completed, failed, success, in progress, location of output etc) -> #510 
- [x] Test duqduq setup changes on gateway from #487 and #502 -> Any issues were fixed by updating the template directly (no changes in duqtools, see https://github.com/duqtools/duqduq_testcase/commit/937be0ce170025474cdff7ff6c534064cfcba76d for more info)

Follows up on: #414

**Comment by stefsmeets** [comment]
Sample use case, `duqduq` should be able to modify the JINTRAC settings using IDS metadata to allow this template to be used for all of the IDSs provided.

template:
```
/pfs/work/g2aho/jetto/runs/runparallel/jet90350/interpretive_esco02/
```

test data:
```
/pfs/work/g2aho/public/imasdb/aug/3/0/ids_369820002.*
/pfs/work/g2aho/public/imasdb/jet/3/0/ids_752250002.*
/pfs/work/g2aho/public/imasdb/jet/3/0/ids_903500002.*
/pfs/work/g2aho/public/imasdb/jet/3/0/ids_924320002.*
/pfs/work/g2aho/public/imasdb/jet/3/0/ids_948750001.*
/pfs/work/g2aho/public/imasdb/tcv/3/0/ids_649580002.*
/pfs/work/g2aho/public/imasdb/west/3/0/ids_545680001.*
/pfs/work/g2aho/public/imasdb/west/3/0/ids_547280001.*
/pfs/work/g2aho/public/imasdb/west/3/0/ids_551810001.*
/pfs/work/g2aho/public/imasdb/west/3/0/ids_555250001.*
```

**Comment by stefsmeets** [comment]
See also #476

**Comment by stefsmeets** [comment]
I'm going to close this, because most of the items in this issue have been completed.
