### ISSUE TITLE
Improvements for IMAS-CI

### ISSUE THREAD

**Issue by v1kko** [duqtools/duqtools#468]
- [x] Remove tkinter install from `test_imas.yaml` once `jetto-pythontools` is updated > #471 
- [x] Cache `.imasenv` -> #470
- [x] Map `/opt/imas/shared` to imasdb in `docker-compose.yaml` for when the user is not root. -> Closed by: https://github.com/duqtools/containerized_runs/pull/4
- [x] This should be our main test, consider running the python version tests only on pushes to main -> #470
- [x] move coverage checking from non-IMAS CI to the IMAS CI -> #470

_Originally posted by @stefsmeets in https://github.com/duqtools/duqtools/pull/466#pullrequestreview-1218888766_

**Comment by stefsmeets** [comment]
That would be a bit of a shame. Can we not install duqtools within a volume and then run the coverage tool there? We need to figure out the path to the covdata and upload it to an artifact.

Relevant link for future reference: https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container

**Comment by v1kko** [comment]
or do a `sudo git checkout` in the same directory as the one in the container, which I tried with:

```yaml     steps:
       - name: Check out the repo
         uses: actions/checkout@v3
         with:
           path: /__w/duqtools/duqtools/
```

**Comment by stefsmeets** [comment]
> or do a `sudo git checkout` in the same directory as the one in the container, which I tried with:
> 
> ```yaml
>        - name: Check out the repo
>          uses: actions/checkout@v3
>          with:
>            path: /__w/duqtools/duqtools/
> ```
> 
> but actions checkout complains that is not "in the working directory" :(

I solved the coverage issue by writing a little python script to update the paths in `.coverage`: https://github.com/duqtools/duqtools/blob/f8e885da8e919694a49415a43db0083be0b7ba0c/.github/workflows/test_imas.yaml#L121-L134
