### ISSUE TITLE
Workshop TODO

### ISSUE THREAD

**Issue by v1kko** [duqtools/duqtools#541]
Our contributions to the integrated modelling workshop:

- [ ] Monday, 15.30: duqtools demonstration (30 min)
- [ ] Monday, 16.00: duqtools training (45 min)
- [x] Tuesday, 15.00: Large scale validation workflow
    - What is our contribution?
- [ ] Wednesday, 9.00: Feedback/thoughts on JINTRAC/IMAS software sustainability (couple of slides) (victor)
- [ ] Wednesday, 13.30: HFPS/duqtools on cloud
- [x] Thursday, 10.00: Duqtools python HLI / visualization IDSs -> notebook
- [ ] Thursday, 10.00: Show IDS manipulation in duqtools, i.e. ImasHandle / IDSMapping / xarray/rebasing? (15 min)
    - Discuss with Advanced Computing Hubs about long term maintenance of duqtools
    - imas/ids directly to xarray would truely be great to have (victors opinion)
- [x] Thursday, 15.00: Large scale validation workflow
    - What is our contribution?

### Demo's

- [x] Check notebooks / python workflows up to date -> #546 
- [x] Prepare demo single run workflow -> #551 
- [x] Prepare demo large-scale-validation workflow -> #553 
- [x] Prepare demo submit to docker / cloud -> #548 
- [x] Run large scale validation with larger time step

### Other

- [x] Make a release (1.6.0) before the workshop

**Comment by stefsmeets** [comment]
Potential IMAS issues to raise:
- Data dimensions are not specified in data dictionary. 
- The grid variable is dependent on the time step, but we need to use it as a dimension (e.g. re-grid `rho_tor_norm` to first time-step for each variable). The grid variable does not vary with time(?).

**Comment by stefsmeets** [comment]
I tried running aron's dataset with a 1 second time step, but I do not see any variation in the data. So it may not be that useful for our demo.
